In [35]:
import numpy as np
import math

In [36]:
x = np.array([50, 60, 70, 80, 90])
y = np.array([40, 70, 90, 60, 100])

In [37]:
x_mean = x.mean() # moyenne de array x # np.mean(x) = x.mean()
x_mean

70.0

In [38]:
y_mean = np.mean(y) # moyenne de array y
y_mean

72.0

In [61]:
xy_covariance = ((x - x_mean) * (y - y_mean)).sum()  # covariance entre x et y
xy_covariance

1100.0

In [62]:
#(x - x_mean)
#x_variance = np.power((x - x_mean), 2).sum() # total de carré de (x - x_mean) = variance de x
#x_variance

In [69]:
x_variance = ((x - x_mean)**2).sum()
x_variance

1000.0

In [70]:
x_root = math.sqrt(x_variance) # racine carrée de variance de x
x_root

31.622776601683793

In [66]:
#(y - y_mean)
#y_variance = np.power((y - y_mean), 2).sum() # total de carré de (y - y_mean) = variance de y
#y_variance

In [71]:
y_variance = ((y - y_mean)**2).sum()
y_variance

2280.0

In [72]:
y_root = math.sqrt(y_variance) # racine carrée de variance de y
y_root

47.74934554525329

In [73]:
r_calcule_manuel = xy_covariance / (x_root * y_root)
r_calcule_manuel

0.728492796385774

In [23]:
x_std = np.std(x) # Écart type (racine carré de variance) de x

In [24]:
y_std = np.std(y) # Écart type (racine carré de variance) de y
y_std

21.354156504062622

In [58]:
xy_cov = np.cov(x, y, bias=True) #Covariance
xy_cov

array([[200., 220.],
       [220., 456.]])

In [26]:
r = xy_cov / (x_std * y_std)
r

array([[0.66226618, 0.7284928 ],
       [0.7284928 , 1.50996689]])

In [29]:
r_2 = np.corrcoef(x, y)
r_2

array([[1.       , 0.7284928],
       [0.7284928, 1.       ]])